from typing import Any, Protocol

from repo_lens.rag.types import IndexedDocument


class SearchIndex(Protocol):
    def add_document(self, document: IndexedDocument) -> None: ...

    def add_documents(self, documents: list[IndexedDocument]) -> None: ...

    def search(
        self, *, query: Any, k: int = 1, repo: str | None = None
    ) -> list[tuple[IndexedDocument, float]]: ...

    def __len__(self) -> int: ...


class Indexer(Protocol):
    def load_from_store(self) -> int: ...
    def exists(self, key: str, value: str) -> bool: ...
    def index(self, documents: list[IndexedDocument]) -> int: ...
    def reindex(
        self, key: str, value: str, documents: list[IndexedDocument]
    ) -> int: ...
    def search(
        self, *, query: str, k: int = 5, repo: str | None = None
    ) -> list[tuple[IndexedDocument, float]]: ...
