from typing import Any, Protocol

from repo_lens.rag.types import IndexedDocument


class SearchIndex(Protocol):
    def add_document(self, document: IndexedDocument) -> None: ...

    def add_documents(self, documents: list[IndexedDocument]) -> None: ...

    def search(
        self, *, query: Any, k: int = 1, repo: str | None = None
    ) -> list[tuple[IndexedDocument, float]]: ...

    def __len__(self) -> int: ...


class Indexer(Protocol):
    def load_from_store(self) -> int: ...
    def file_is_indexed(self, repo: str, path: str) -> bool: ...
    def index_file(
        self, repo: str, path: str, documents: list[IndexedDocument]
    ) -> int: ...
    def clear_repo(self, repo: str) -> int: ...
    def search(
        self, *, query: str, k: int = 5, repo: str | None = None
    ) -> list[tuple[IndexedDocument, float]]: ...
