from typing import Any, Protocol


class SearchIndex(Protocol):
    def add_document(self, document: dict[str, Any]) -> None: ...

    def add_documents(self, documents: list[dict[str, Any]]) -> None: ...

    def search(self, query: Any, k: int = 1) -> list[tuple[dict[str, Any], float]]: ...

    def __len__(self) -> int: ...


class Indexer(Protocol):
    def load_from_store(self) -> int: ...
    def exists(self, key: str, value: str) -> bool: ...
    def index(self, documents: list[dict[str, Any]]) -> int: ...
    def reindex(self, key: str, value: str, documents: list[dict[str, Any]]) -> int: ...
    def search(self, query: str, k: int = 5) -> list[tuple[dict[str, Any], float]]: ...
